name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: lab5a
      id: lab5a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lab5a
        setup-command: ''
        command: python3 ./CheckLab5.py -f -v lab5a
        timeout: 10
        max-score: 1
    - name: lab5b
      id: lab5b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lab5b
        setup-command: ''
        command: python3 ./CheckLab5.py -f -v lab5b
        timeout: 10
        max-score: 1
    - name: lab5c
      id: lab5c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: lab5c
        setup-command: ''
        command: python3 ./CheckLab5.py -f -v lab5c
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB5A_RESULTS: "${{steps.lab5a.outputs.result}}"
        LAB5B_RESULTS: "${{steps.lab5b.outputs.result}}"
        LAB5C_RESULTS: "${{steps.lab5c.outputs.result}}"
      with:
        runners: lab5a,lab5b,lab5c
